# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-16 05:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app001', '0003_auto_20160816_0517'),
    ]

    operations = [
        migrations.AddField(
            model_name='item000',
            name='field6',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
