# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-16 05:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app001', '0004_item000_field6'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='spec',
            name='field4',
        ),
        migrations.RemoveField(
            model_name='spec',
            name='field5',
        ),
    ]
