# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-16 06:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app001', '0005_auto_20160816_0557'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spec',
            name='field3',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
