# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-16 09:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app001', '0008_auto_20160816_0853'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cust',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field1', models.IntegerField()),
                ('field2', models.CharField(max_length=200)),
                ('field3', models.CharField(max_length=200, null=True)),
            ],
        ),
    ]
