# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-17 00:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app001', '0011_auto_20160816_1022'),
    ]

    operations = [
        migrations.AddField(
            model_name='item001',
            name='field1a',
            field=models.CharField(default='.', max_length=200, verbose_name='噸位'),
        ),
        migrations.AddField(
            model_name='item001',
            name='field6',
            field=models.CharField(blank=True, max_length=200, verbose_name='客訴量'),
        ),
        migrations.AddField(
            model_name='item001',
            name='field7',
            field=models.CharField(blank=True, max_length=200, verbose_name='模具壽命'),
        ),
        migrations.AlterField(
            model_name='item001',
            name='field1',
            field=models.CharField(max_length=200, verbose_name='壓鑄機編號'),
        ),
        migrations.AlterField(
            model_name='item001',
            name='field2',
            field=models.CharField(max_length=200, verbose_name='客戶'),
        ),
        migrations.AlterField(
            model_name='item001',
            name='field3',
            field=models.CharField(max_length=200, verbose_name='品名'),
        ),
        migrations.AlterField(
            model_name='item001',
            name='field4',
            field=models.CharField(max_length=200, verbose_name='欠料量'),
        ),
        migrations.AlterField(
            model_name='item001',
            name='field5',
            field=models.CharField(max_length=200, verbose_name='欠備庫量'),
        ),
    ]
