# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-17 00:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app001', '0013_auto_20160817_0034'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item001',
            name='id',
        ),
        migrations.AlterField(
            model_name='item001',
            name='field1',
            field=models.CharField(max_length=200, primary_key=True, serialize=False, verbose_name='壓鑄機編號'),
        ),
        migrations.AlterField(
            model_name='item001',
            name='field6',
            field=models.CharField(default='.', max_length=200, null=True, verbose_name='客訴量'),
        ),
        migrations.AlterField(
            model_name='item001',
            name='field7',
            field=models.CharField(default='.', max_length=200, null=True, verbose_name='模具壽命'),
        ),
    ]
