# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-17 03:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app001', '0017_auto_20160817_0151'),
    ]

    operations = [
        migrations.AddField(
            model_name='item001',
            name='r01c6',
            field=models.CharField(default='.', max_length=99, verbose_name='人員'),
        ),
        migrations.AddField(
            model_name='item001',
            name='r01c8',
            field=models.CharField(default='.', max_length=99, verbose_name='日期'),
        ),
    ]
