# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-17 03:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app001', '0018_auto_20160817_0325'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item001',
            name='field2a1',
        ),
        migrations.RemoveField(
            model_name='item001',
            name='field2a2',
        ),
        migrations.RemoveField(
            model_name='item001',
            name='field2a3',
        ),
        migrations.RemoveField(
            model_name='item001',
            name='field2a4',
        ),
        migrations.RemoveField(
            model_name='item001',
            name='field2a5',
        ),
        migrations.RemoveField(
            model_name='item001',
            name='field2a6',
        ),
        migrations.RemoveField(
            model_name='item001',
            name='field2b1',
        ),
        migrations.RemoveField(
            model_name='item001',
            name='field2b2',
        ),
        migrations.RemoveField(
            model_name='item001',
            name='field2b3',
        ),
        migrations.RemoveField(
            model_name='item001',
            name='field2b4',
        ),
        migrations.RemoveField(
            model_name='item001',
            name='field2c1',
        ),
        migrations.RemoveField(
            model_name='item001',
            name='field2d1',
        ),
        migrations.RemoveField(
            model_name='item001',
            name='field2e1',
        ),
        migrations.RemoveField(
            model_name='item001',
            name='field2f1',
        ),
        migrations.RemoveField(
            model_name='item001',
            name='field2g1',
        ),
        migrations.RemoveField(
            model_name='item001',
            name='field2h1',
        ),
        migrations.RemoveField(
            model_name='item001',
            name='field3',
        ),
        migrations.RemoveField(
            model_name='item001',
            name='field4a',
        ),
        migrations.RemoveField(
            model_name='item001',
            name='field4b',
        ),
        migrations.RemoveField(
            model_name='item001',
            name='field4c',
        ),
        migrations.AddField(
            model_name='item001',
            name='r03c3',
            field=models.CharField(default='.', max_length=99, verbose_name='格林柱-零件'),
        ),
        migrations.AddField(
            model_name='item001',
            name='r03c4',
            field=models.CharField(default='.', max_length=99, verbose_name='格林柱-進度一'),
        ),
        migrations.AddField(
            model_name='item001',
            name='r03c5',
            field=models.CharField(default='.', max_length=99, verbose_name='格林柱-進度二'),
        ),
        migrations.AddField(
            model_name='item001',
            name='r03c6',
            field=models.CharField(default='.', max_length=99, verbose_name='格林柱-進度三'),
        ),
        migrations.AddField(
            model_name='item001',
            name='r03c7',
            field=models.CharField(default='.', max_length=99, verbose_name='格林柱-備註說明'),
        ),
        migrations.AddField(
            model_name='item001',
            name='r04c3',
            field=models.CharField(default='.', max_length=99, verbose_name='機架底座-零件'),
        ),
        migrations.AddField(
            model_name='item001',
            name='r04c4',
            field=models.CharField(default='.', max_length=99, verbose_name='機架底座-進度一'),
        ),
        migrations.AddField(
            model_name='item001',
            name='r04c5',
            field=models.CharField(default='.', max_length=99, verbose_name='機架底座-進度二'),
        ),
        migrations.AddField(
            model_name='item001',
            name='r04c6',
            field=models.CharField(default='.', max_length=99, verbose_name='機架底座-進度三'),
        ),
        migrations.AddField(
            model_name='item001',
            name='r04c7',
            field=models.CharField(default='.', max_length=99, verbose_name='機架底座-備註說明'),
        ),
    ]
