# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-17 05:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app001', '0019_auto_20160817_0343'),
    ]

    operations = [
        migrations.AddField(
            model_name='item001',
            name='r05c3',
            field=models.CharField(default='.', max_length=99, verbose_name='機架底座-零件'),
        ),
        migrations.AddField(
            model_name='item001',
            name='r05c4',
            field=models.CharField(default='.', max_length=99, verbose_name='機架底座-進度一'),
        ),
        migrations.AddField(
            model_name='item001',
            name='r05c5',
            field=models.CharField(default='.', max_length=99, verbose_name='機架底座-進度二'),
        ),
        migrations.AddField(
            model_name='item001',
            name='r05c6',
            field=models.CharField(default='.', max_length=99, verbose_name='機架底座-進度三'),
        ),
        migrations.AddField(
            model_name='item001',
            name='r05c7',
            field=models.CharField(default='.', max_length=99, verbose_name='機架底座-備註說明'),
        ),
        migrations.AddField(
            model_name='item001',
            name='r06c3',
            field=models.CharField(default='.', max_length=99, verbose_name='機架底座-零件'),
        ),
        migrations.AddField(
            model_name='item001',
            name='r06c4',
            field=models.CharField(default='.', max_length=99, verbose_name='機架底座-進度一'),
        ),
        migrations.AddField(
            model_name='item001',
            name='r06c5',
            field=models.CharField(default='.', max_length=99, verbose_name='機架底座-進度二'),
        ),
        migrations.AddField(
            model_name='item001',
            name='r06c6',
            field=models.CharField(default='.', max_length=99, verbose_name='機架底座-進度三'),
        ),
        migrations.AddField(
            model_name='item001',
            name='r06c7',
            field=models.CharField(default='.', max_length=99, verbose_name='機架底座-備註說明'),
        ),
        migrations.AddField(
            model_name='item001',
            name='r07c3',
            field=models.CharField(default='.', max_length=99, verbose_name='機架底座-零件'),
        ),
        migrations.AddField(
            model_name='item001',
            name='r07c4',
            field=models.CharField(default='.', max_length=99, verbose_name='機架底座-進度一'),
        ),
        migrations.AddField(
            model_name='item001',
            name='r07c5',
            field=models.CharField(default='.', max_length=99, verbose_name='機架底座-進度二'),
        ),
        migrations.AddField(
            model_name='item001',
            name='r07c6',
            field=models.CharField(default='.', max_length=99, verbose_name='機架底座-進度三'),
        ),
        migrations.AddField(
            model_name='item001',
            name='r07c7',
            field=models.CharField(default='.', max_length=99, verbose_name='機架底座-備註說明'),
        ),
        migrations.AddField(
            model_name='item001',
            name='r08c3',
            field=models.CharField(default='.', max_length=99, verbose_name='機架底座-零件'),
        ),
        migrations.AddField(
            model_name='item001',
            name='r08c4',
            field=models.CharField(default='.', max_length=99, verbose_name='機架底座-進度一'),
        ),
        migrations.AddField(
            model_name='item001',
            name='r08c5',
            field=models.CharField(default='.', max_length=99, verbose_name='機架底座-進度二'),
        ),
        migrations.AddField(
            model_name='item001',
            name='r08c6',
            field=models.CharField(default='.', max_length=99, verbose_name='機架底座-進度三'),
        ),
        migrations.AddField(
            model_name='item001',
            name='r08c7',
            field=models.CharField(default='.', max_length=99, verbose_name='機架底座-備註說明'),
        ),
    ]
