# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-17 05:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app001', '0020_auto_20160817_0524'),
    ]

    operations = [
        migrations.AddField(
            model_name='item001',
            name='r10c3',
            field=models.CharField(default='.', max_length=99, verbose_name='膜厚調節-零件'),
        ),
        migrations.AddField(
            model_name='item001',
            name='r10c4',
            field=models.CharField(default='.', max_length=99, verbose_name='膜厚調節-進度一'),
        ),
        migrations.AddField(
            model_name='item001',
            name='r10c5',
            field=models.CharField(default='.', max_length=99, verbose_name='膜厚調節-進度二'),
        ),
        migrations.AddField(
            model_name='item001',
            name='r10c6',
            field=models.CharField(default='.', max_length=99, verbose_name='膜厚調節-進度三'),
        ),
        migrations.AddField(
            model_name='item001',
            name='r10c7',
            field=models.CharField(default='.', max_length=99, verbose_name='膜厚調節-備註說明'),
        ),
        migrations.AddField(
            model_name='item001',
            name='r11c3',
            field=models.CharField(default='.', max_length=99, verbose_name='過濾-零件'),
        ),
        migrations.AddField(
            model_name='item001',
            name='r11c4',
            field=models.CharField(default='.', max_length=99, verbose_name='過濾-進度一'),
        ),
        migrations.AddField(
            model_name='item001',
            name='r11c5',
            field=models.CharField(default='.', max_length=99, verbose_name='過濾-進度二'),
        ),
        migrations.AddField(
            model_name='item001',
            name='r11c6',
            field=models.CharField(default='.', max_length=99, verbose_name='過濾-進度三'),
        ),
        migrations.AddField(
            model_name='item001',
            name='r11c7',
            field=models.CharField(default='.', max_length=99, verbose_name='過濾-備註說明'),
        ),
        migrations.AddField(
            model_name='item001',
            name='r12c3',
            field=models.CharField(default='.', max_length=99, verbose_name='油箱-零件'),
        ),
        migrations.AddField(
            model_name='item001',
            name='r12c4',
            field=models.CharField(default='.', max_length=99, verbose_name='油箱-進度一'),
        ),
        migrations.AddField(
            model_name='item001',
            name='r12c5',
            field=models.CharField(default='.', max_length=99, verbose_name='油箱-進度二'),
        ),
        migrations.AddField(
            model_name='item001',
            name='r12c6',
            field=models.CharField(default='.', max_length=99, verbose_name='油箱-進度三'),
        ),
        migrations.AddField(
            model_name='item001',
            name='r12c7',
            field=models.CharField(default='.', max_length=99, verbose_name='油箱-備註說明'),
        ),
        migrations.AddField(
            model_name='item001',
            name='r13c3',
            field=models.CharField(default='.', max_length=99, verbose_name='馬達-零件'),
        ),
        migrations.AddField(
            model_name='item001',
            name='r13c4',
            field=models.CharField(default='.', max_length=99, verbose_name='馬達-進度一'),
        ),
        migrations.AddField(
            model_name='item001',
            name='r13c5',
            field=models.CharField(default='.', max_length=99, verbose_name='馬達-進度二'),
        ),
        migrations.AddField(
            model_name='item001',
            name='r13c6',
            field=models.CharField(default='.', max_length=99, verbose_name='馬達-進度三'),
        ),
        migrations.AddField(
            model_name='item001',
            name='r13c7',
            field=models.CharField(default='.', max_length=99, verbose_name='馬達-備註說明'),
        ),
        migrations.AddField(
            model_name='item001',
            name='r15c3',
            field=models.CharField(default='.', max_length=99, verbose_name='潤滑-零件'),
        ),
        migrations.AddField(
            model_name='item001',
            name='r15c4',
            field=models.CharField(default='.', max_length=99, verbose_name='潤滑-進度一'),
        ),
        migrations.AddField(
            model_name='item001',
            name='r15c5',
            field=models.CharField(default='.', max_length=99, verbose_name='潤滑-進度二'),
        ),
        migrations.AddField(
            model_name='item001',
            name='r15c6',
            field=models.CharField(default='.', max_length=99, verbose_name='潤滑-進度三'),
        ),
        migrations.AddField(
            model_name='item001',
            name='r15c7',
            field=models.CharField(default='.', max_length=99, verbose_name='潤滑-備註說明'),
        ),
        migrations.AddField(
            model_name='item001',
            name='r16c3',
            field=models.CharField(default='.', max_length=99, verbose_name='氮氣-零件'),
        ),
        migrations.AddField(
            model_name='item001',
            name='r16c4',
            field=models.CharField(default='.', max_length=99, verbose_name='氮氣-進度一'),
        ),
        migrations.AddField(
            model_name='item001',
            name='r16c5',
            field=models.CharField(default='.', max_length=99, verbose_name='氮氣-進度二'),
        ),
        migrations.AddField(
            model_name='item001',
            name='r16c6',
            field=models.CharField(default='.', max_length=99, verbose_name='氮氣-進度三'),
        ),
        migrations.AddField(
            model_name='item001',
            name='r16c7',
            field=models.CharField(default='.', max_length=99, verbose_name='氮氣-備註說明'),
        ),
        migrations.AddField(
            model_name='item001',
            name='r17c3',
            field=models.CharField(default='.', max_length=99, verbose_name='電控-零件'),
        ),
        migrations.AddField(
            model_name='item001',
            name='r17c4',
            field=models.CharField(default='.', max_length=99, verbose_name='電控-進度一'),
        ),
        migrations.AddField(
            model_name='item001',
            name='r17c5',
            field=models.CharField(default='.', max_length=99, verbose_name='電控-進度二'),
        ),
        migrations.AddField(
            model_name='item001',
            name='r17c6',
            field=models.CharField(default='.', max_length=99, verbose_name='電控-進度三'),
        ),
        migrations.AddField(
            model_name='item001',
            name='r17c7',
            field=models.CharField(default='.', max_length=99, verbose_name='電控-備註說明'),
        ),
        migrations.AddField(
            model_name='item001',
            name='r18c3',
            field=models.CharField(default='.', max_length=99, verbose_name='自動噴霧-零件'),
        ),
        migrations.AddField(
            model_name='item001',
            name='r18c4',
            field=models.CharField(default='.', max_length=99, verbose_name='自動噴霧-進度一'),
        ),
        migrations.AddField(
            model_name='item001',
            name='r18c5',
            field=models.CharField(default='.', max_length=99, verbose_name='自動噴霧-進度二'),
        ),
        migrations.AddField(
            model_name='item001',
            name='r18c6',
            field=models.CharField(default='.', max_length=99, verbose_name='自動噴霧-進度三'),
        ),
        migrations.AddField(
            model_name='item001',
            name='r18c7',
            field=models.CharField(default='.', max_length=99, verbose_name='自動噴霧-備註說明'),
        ),
        migrations.AddField(
            model_name='item001',
            name='r19c3',
            field=models.CharField(default='.', max_length=99, verbose_name='自動取出-零件'),
        ),
        migrations.AddField(
            model_name='item001',
            name='r19c4',
            field=models.CharField(default='.', max_length=99, verbose_name='自動取出-進度一'),
        ),
        migrations.AddField(
            model_name='item001',
            name='r19c5',
            field=models.CharField(default='.', max_length=99, verbose_name='自動取出-進度二'),
        ),
        migrations.AddField(
            model_name='item001',
            name='r19c6',
            field=models.CharField(default='.', max_length=99, verbose_name='自動取出-進度三'),
        ),
        migrations.AddField(
            model_name='item001',
            name='r19c7',
            field=models.CharField(default='.', max_length=99, verbose_name='自動取出-備註說明'),
        ),
        migrations.AddField(
            model_name='item001',
            name='r20c3',
            field=models.CharField(default='.', max_length=99, verbose_name='自動切邊去毛-零件'),
        ),
        migrations.AddField(
            model_name='item001',
            name='r20c4',
            field=models.CharField(default='.', max_length=99, verbose_name='自動切邊去毛-進度一'),
        ),
        migrations.AddField(
            model_name='item001',
            name='r20c5',
            field=models.CharField(default='.', max_length=99, verbose_name='自動切邊去毛-進度二'),
        ),
        migrations.AddField(
            model_name='item001',
            name='r20c6',
            field=models.CharField(default='.', max_length=99, verbose_name='自動切邊去毛-進度三'),
        ),
        migrations.AddField(
            model_name='item001',
            name='r20c7',
            field=models.CharField(default='.', max_length=99, verbose_name='自動切邊去毛-備註說明'),
        ),
        migrations.AlterField(
            model_name='item001',
            name='r05c3',
            field=models.CharField(default='.', max_length=99, verbose_name='模板-零件'),
        ),
        migrations.AlterField(
            model_name='item001',
            name='r05c4',
            field=models.CharField(default='.', max_length=99, verbose_name='模板-進度一'),
        ),
        migrations.AlterField(
            model_name='item001',
            name='r05c5',
            field=models.CharField(default='.', max_length=99, verbose_name='模板-進度二'),
        ),
        migrations.AlterField(
            model_name='item001',
            name='r05c6',
            field=models.CharField(default='.', max_length=99, verbose_name='模板-進度三'),
        ),
        migrations.AlterField(
            model_name='item001',
            name='r05c7',
            field=models.CharField(default='.', max_length=99, verbose_name='模板-備註說明'),
        ),
        migrations.AlterField(
            model_name='item001',
            name='r06c3',
            field=models.CharField(default='.', max_length=99, verbose_name='合模-零件'),
        ),
        migrations.AlterField(
            model_name='item001',
            name='r06c4',
            field=models.CharField(default='.', max_length=99, verbose_name='合模-進度一'),
        ),
        migrations.AlterField(
            model_name='item001',
            name='r06c5',
            field=models.CharField(default='.', max_length=99, verbose_name='合模-進度二'),
        ),
        migrations.AlterField(
            model_name='item001',
            name='r06c6',
            field=models.CharField(default='.', max_length=99, verbose_name='合模-進度三'),
        ),
        migrations.AlterField(
            model_name='item001',
            name='r06c7',
            field=models.CharField(default='.', max_length=99, verbose_name='合模-備註說明'),
        ),
        migrations.AlterField(
            model_name='item001',
            name='r07c3',
            field=models.CharField(default='.', max_length=99, verbose_name='模板-零件'),
        ),
        migrations.AlterField(
            model_name='item001',
            name='r07c4',
            field=models.CharField(default='.', max_length=99, verbose_name='模板-進度一'),
        ),
        migrations.AlterField(
            model_name='item001',
            name='r07c5',
            field=models.CharField(default='.', max_length=99, verbose_name='模板-進度二'),
        ),
        migrations.AlterField(
            model_name='item001',
            name='r07c6',
            field=models.CharField(default='.', max_length=99, verbose_name='模板-進度三'),
        ),
        migrations.AlterField(
            model_name='item001',
            name='r07c7',
            field=models.CharField(default='.', max_length=99, verbose_name='模板-備註說明'),
        ),
        migrations.AlterField(
            model_name='item001',
            name='r08c3',
            field=models.CharField(default='.', max_length=99, verbose_name='間隙-零件'),
        ),
        migrations.AlterField(
            model_name='item001',
            name='r08c4',
            field=models.CharField(default='.', max_length=99, verbose_name='間隙-進度一'),
        ),
        migrations.AlterField(
            model_name='item001',
            name='r08c5',
            field=models.CharField(default='.', max_length=99, verbose_name='間隙-進度二'),
        ),
        migrations.AlterField(
            model_name='item001',
            name='r08c6',
            field=models.CharField(default='.', max_length=99, verbose_name='間隙-進度三'),
        ),
        migrations.AlterField(
            model_name='item001',
            name='r08c7',
            field=models.CharField(default='.', max_length=99, verbose_name='間隙-備註說明'),
        ),
    ]
