# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-17 06:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app001', '0021_auto_20160817_0556'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item001',
            name='r07c3',
            field=models.CharField(default='.', max_length=99, verbose_name='間隙-零件'),
        ),
        migrations.AlterField(
            model_name='item001',
            name='r07c4',
            field=models.CharField(default='.', max_length=99, verbose_name='間隙-進度一'),
        ),
        migrations.AlterField(
            model_name='item001',
            name='r07c5',
            field=models.CharField(default='.', max_length=99, verbose_name='間隙-進度二'),
        ),
        migrations.AlterField(
            model_name='item001',
            name='r07c6',
            field=models.CharField(default='.', max_length=99, verbose_name='間隙-進度三'),
        ),
        migrations.AlterField(
            model_name='item001',
            name='r07c7',
            field=models.CharField(default='.', max_length=99, verbose_name='間隙-備註說明'),
        ),
        migrations.AlterField(
            model_name='item001',
            name='r08c3',
            field=models.CharField(default='.', max_length=99, verbose_name='膜厚調節-零件'),
        ),
        migrations.AlterField(
            model_name='item001',
            name='r08c4',
            field=models.CharField(default='.', max_length=99, verbose_name='膜厚調節-進度一'),
        ),
        migrations.AlterField(
            model_name='item001',
            name='r08c5',
            field=models.CharField(default='.', max_length=99, verbose_name='膜厚調節-進度二'),
        ),
        migrations.AlterField(
            model_name='item001',
            name='r08c6',
            field=models.CharField(default='.', max_length=99, verbose_name='膜厚調節-進度三'),
        ),
        migrations.AlterField(
            model_name='item001',
            name='r08c7',
            field=models.CharField(default='.', max_length=99, verbose_name='膜厚調節-備註說明'),
        ),
        migrations.AlterField(
            model_name='item001',
            name='r10c3',
            field=models.CharField(default='.', max_length=99, verbose_name='油管-零件'),
        ),
        migrations.AlterField(
            model_name='item001',
            name='r10c4',
            field=models.CharField(default='.', max_length=99, verbose_name='油管-進度一'),
        ),
        migrations.AlterField(
            model_name='item001',
            name='r10c5',
            field=models.CharField(default='.', max_length=99, verbose_name='油管-進度二'),
        ),
        migrations.AlterField(
            model_name='item001',
            name='r10c6',
            field=models.CharField(default='.', max_length=99, verbose_name='油管-進度三'),
        ),
        migrations.AlterField(
            model_name='item001',
            name='r10c7',
            field=models.CharField(default='.', max_length=99, verbose_name='油管-備註說明'),
        ),
    ]
