# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-17 08:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app001', '0023_auto_20160817_0805'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item004',
            name='id',
        ),
        migrations.AlterField(
            model_name='item004',
            name='field1',
            field=models.CharField(max_length=200, primary_key=True, serialize=False, verbose_name='編號'),
        ),
    ]
