# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-17 08:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app001', '0025_auto_20160817_0812'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item003',
            name='field2a1',
        ),
        migrations.RemoveField(
            model_name='item003',
            name='field2a2',
        ),
        migrations.RemoveField(
            model_name='item003',
            name='field2a3',
        ),
        migrations.RemoveField(
            model_name='item003',
            name='field2a4',
        ),
        migrations.RemoveField(
            model_name='item003',
            name='field2a5',
        ),
        migrations.RemoveField(
            model_name='item003',
            name='field2a6',
        ),
        migrations.RemoveField(
            model_name='item003',
            name='field2b1',
        ),
        migrations.RemoveField(
            model_name='item003',
            name='field2b2',
        ),
        migrations.RemoveField(
            model_name='item003',
            name='field2b3',
        ),
        migrations.RemoveField(
            model_name='item003',
            name='field2b4',
        ),
        migrations.RemoveField(
            model_name='item003',
            name='field2c1',
        ),
        migrations.RemoveField(
            model_name='item003',
            name='field2d1',
        ),
        migrations.RemoveField(
            model_name='item003',
            name='field2e1',
        ),
        migrations.RemoveField(
            model_name='item003',
            name='field2f1',
        ),
        migrations.RemoveField(
            model_name='item003',
            name='field2g1',
        ),
        migrations.RemoveField(
            model_name='item003',
            name='field2h1',
        ),
        migrations.RemoveField(
            model_name='item003',
            name='field3',
        ),
        migrations.RemoveField(
            model_name='item003',
            name='field4a',
        ),
        migrations.RemoveField(
            model_name='item003',
            name='field4b',
        ),
        migrations.RemoveField(
            model_name='item003',
            name='field4c',
        ),
        migrations.AddField(
            model_name='item003',
            name='r01c6',
            field=models.CharField(default='.', max_length=99, verbose_name='人員'),
        ),
        migrations.AddField(
            model_name='item003',
            name='r01c8',
            field=models.CharField(default='.', max_length=99, verbose_name='日期'),
        ),
        migrations.AddField(
            model_name='item003',
            name='r03c3',
            field=models.CharField(default='.', max_length=99, verbose_name='格林柱-零件'),
        ),
        migrations.AddField(
            model_name='item003',
            name='r03c4',
            field=models.CharField(default='.', max_length=99, verbose_name='格林柱-進度一'),
        ),
        migrations.AddField(
            model_name='item003',
            name='r03c5',
            field=models.CharField(default='.', max_length=99, verbose_name='格林柱-進度二'),
        ),
        migrations.AddField(
            model_name='item003',
            name='r03c6',
            field=models.CharField(default='.', max_length=99, verbose_name='格林柱-進度三'),
        ),
        migrations.AddField(
            model_name='item003',
            name='r03c7',
            field=models.CharField(default='.', max_length=99, verbose_name='格林柱-備註說明'),
        ),
        migrations.AddField(
            model_name='item003',
            name='r04c3',
            field=models.CharField(default='.', max_length=99, verbose_name='機架底座-零件'),
        ),
        migrations.AddField(
            model_name='item003',
            name='r04c4',
            field=models.CharField(default='.', max_length=99, verbose_name='機架底座-進度一'),
        ),
        migrations.AddField(
            model_name='item003',
            name='r04c5',
            field=models.CharField(default='.', max_length=99, verbose_name='機架底座-進度二'),
        ),
        migrations.AddField(
            model_name='item003',
            name='r04c6',
            field=models.CharField(default='.', max_length=99, verbose_name='機架底座-進度三'),
        ),
        migrations.AddField(
            model_name='item003',
            name='r04c7',
            field=models.CharField(default='.', max_length=99, verbose_name='機架底座-備註說明'),
        ),
        migrations.AddField(
            model_name='item003',
            name='r05c3',
            field=models.CharField(default='.', max_length=99, verbose_name='模板-零件'),
        ),
        migrations.AddField(
            model_name='item003',
            name='r05c4',
            field=models.CharField(default='.', max_length=99, verbose_name='模板-進度一'),
        ),
        migrations.AddField(
            model_name='item003',
            name='r05c5',
            field=models.CharField(default='.', max_length=99, verbose_name='模板-進度二'),
        ),
        migrations.AddField(
            model_name='item003',
            name='r05c6',
            field=models.CharField(default='.', max_length=99, verbose_name='模板-進度三'),
        ),
        migrations.AddField(
            model_name='item003',
            name='r05c7',
            field=models.CharField(default='.', max_length=99, verbose_name='模板-備註說明'),
        ),
        migrations.AddField(
            model_name='item003',
            name='r06c3',
            field=models.CharField(default='.', max_length=99, verbose_name='合模-零件'),
        ),
        migrations.AddField(
            model_name='item003',
            name='r06c4',
            field=models.CharField(default='.', max_length=99, verbose_name='合模-進度一'),
        ),
        migrations.AddField(
            model_name='item003',
            name='r06c5',
            field=models.CharField(default='.', max_length=99, verbose_name='合模-進度二'),
        ),
        migrations.AddField(
            model_name='item003',
            name='r06c6',
            field=models.CharField(default='.', max_length=99, verbose_name='合模-進度三'),
        ),
        migrations.AddField(
            model_name='item003',
            name='r06c7',
            field=models.CharField(default='.', max_length=99, verbose_name='合模-備註說明'),
        ),
        migrations.AddField(
            model_name='item003',
            name='r07c3',
            field=models.CharField(default='.', max_length=99, verbose_name='間隙-零件'),
        ),
        migrations.AddField(
            model_name='item003',
            name='r07c4',
            field=models.CharField(default='.', max_length=99, verbose_name='間隙-進度一'),
        ),
        migrations.AddField(
            model_name='item003',
            name='r07c5',
            field=models.CharField(default='.', max_length=99, verbose_name='間隙-進度二'),
        ),
        migrations.AddField(
            model_name='item003',
            name='r07c6',
            field=models.CharField(default='.', max_length=99, verbose_name='間隙-進度三'),
        ),
        migrations.AddField(
            model_name='item003',
            name='r07c7',
            field=models.CharField(default='.', max_length=99, verbose_name='間隙-備註說明'),
        ),
        migrations.AddField(
            model_name='item003',
            name='r08c3',
            field=models.CharField(default='.', max_length=99, verbose_name='膜厚調節-零件'),
        ),
        migrations.AddField(
            model_name='item003',
            name='r08c4',
            field=models.CharField(default='.', max_length=99, verbose_name='膜厚調節-進度一'),
        ),
        migrations.AddField(
            model_name='item003',
            name='r08c5',
            field=models.CharField(default='.', max_length=99, verbose_name='膜厚調節-進度二'),
        ),
        migrations.AddField(
            model_name='item003',
            name='r08c6',
            field=models.CharField(default='.', max_length=99, verbose_name='膜厚調節-進度三'),
        ),
        migrations.AddField(
            model_name='item003',
            name='r08c7',
            field=models.CharField(default='.', max_length=99, verbose_name='膜厚調節-備註說明'),
        ),
        migrations.AddField(
            model_name='item003',
            name='r10c3',
            field=models.CharField(default='.', max_length=99, verbose_name='油管-零件'),
        ),
        migrations.AddField(
            model_name='item003',
            name='r10c4',
            field=models.CharField(default='.', max_length=99, verbose_name='油管-進度一'),
        ),
        migrations.AddField(
            model_name='item003',
            name='r10c5',
            field=models.CharField(default='.', max_length=99, verbose_name='油管-進度二'),
        ),
        migrations.AddField(
            model_name='item003',
            name='r10c6',
            field=models.CharField(default='.', max_length=99, verbose_name='油管-進度三'),
        ),
        migrations.AddField(
            model_name='item003',
            name='r10c7',
            field=models.CharField(default='.', max_length=99, verbose_name='油管-備註說明'),
        ),
        migrations.AddField(
            model_name='item003',
            name='r11c3',
            field=models.CharField(default='.', max_length=99, verbose_name='過濾-零件'),
        ),
        migrations.AddField(
            model_name='item003',
            name='r11c4',
            field=models.CharField(default='.', max_length=99, verbose_name='過濾-進度一'),
        ),
        migrations.AddField(
            model_name='item003',
            name='r11c5',
            field=models.CharField(default='.', max_length=99, verbose_name='過濾-進度二'),
        ),
        migrations.AddField(
            model_name='item003',
            name='r11c6',
            field=models.CharField(default='.', max_length=99, verbose_name='過濾-進度三'),
        ),
        migrations.AddField(
            model_name='item003',
            name='r11c7',
            field=models.CharField(default='.', max_length=99, verbose_name='過濾-備註說明'),
        ),
        migrations.AddField(
            model_name='item003',
            name='r12c3',
            field=models.CharField(default='.', max_length=99, verbose_name='油箱-零件'),
        ),
        migrations.AddField(
            model_name='item003',
            name='r12c4',
            field=models.CharField(default='.', max_length=99, verbose_name='油箱-進度一'),
        ),
        migrations.AddField(
            model_name='item003',
            name='r12c5',
            field=models.CharField(default='.', max_length=99, verbose_name='油箱-進度二'),
        ),
        migrations.AddField(
            model_name='item003',
            name='r12c6',
            field=models.CharField(default='.', max_length=99, verbose_name='油箱-進度三'),
        ),
        migrations.AddField(
            model_name='item003',
            name='r12c7',
            field=models.CharField(default='.', max_length=99, verbose_name='油箱-備註說明'),
        ),
        migrations.AddField(
            model_name='item003',
            name='r13c3',
            field=models.CharField(default='.', max_length=99, verbose_name='馬達-零件'),
        ),
        migrations.AddField(
            model_name='item003',
            name='r13c4',
            field=models.CharField(default='.', max_length=99, verbose_name='馬達-進度一'),
        ),
        migrations.AddField(
            model_name='item003',
            name='r13c5',
            field=models.CharField(default='.', max_length=99, verbose_name='馬達-進度二'),
        ),
        migrations.AddField(
            model_name='item003',
            name='r13c6',
            field=models.CharField(default='.', max_length=99, verbose_name='馬達-進度三'),
        ),
        migrations.AddField(
            model_name='item003',
            name='r13c7',
            field=models.CharField(default='.', max_length=99, verbose_name='馬達-備註說明'),
        ),
        migrations.AddField(
            model_name='item003',
            name='r15c3',
            field=models.CharField(default='.', max_length=99, verbose_name='潤滑-零件'),
        ),
        migrations.AddField(
            model_name='item003',
            name='r15c4',
            field=models.CharField(default='.', max_length=99, verbose_name='潤滑-進度一'),
        ),
        migrations.AddField(
            model_name='item003',
            name='r15c5',
            field=models.CharField(default='.', max_length=99, verbose_name='潤滑-進度二'),
        ),
        migrations.AddField(
            model_name='item003',
            name='r15c6',
            field=models.CharField(default='.', max_length=99, verbose_name='潤滑-進度三'),
        ),
        migrations.AddField(
            model_name='item003',
            name='r15c7',
            field=models.CharField(default='.', max_length=99, verbose_name='潤滑-備註說明'),
        ),
        migrations.AddField(
            model_name='item003',
            name='r16c3',
            field=models.CharField(default='.', max_length=99, verbose_name='氮氣-零件'),
        ),
        migrations.AddField(
            model_name='item003',
            name='r16c4',
            field=models.CharField(default='.', max_length=99, verbose_name='氮氣-進度一'),
        ),
        migrations.AddField(
            model_name='item003',
            name='r16c5',
            field=models.CharField(default='.', max_length=99, verbose_name='氮氣-進度二'),
        ),
        migrations.AddField(
            model_name='item003',
            name='r16c6',
            field=models.CharField(default='.', max_length=99, verbose_name='氮氣-進度三'),
        ),
        migrations.AddField(
            model_name='item003',
            name='r16c7',
            field=models.CharField(default='.', max_length=99, verbose_name='氮氣-備註說明'),
        ),
        migrations.AddField(
            model_name='item003',
            name='r17c3',
            field=models.CharField(default='.', max_length=99, verbose_name='電控-零件'),
        ),
        migrations.AddField(
            model_name='item003',
            name='r17c4',
            field=models.CharField(default='.', max_length=99, verbose_name='電控-進度一'),
        ),
        migrations.AddField(
            model_name='item003',
            name='r17c5',
            field=models.CharField(default='.', max_length=99, verbose_name='電控-進度二'),
        ),
        migrations.AddField(
            model_name='item003',
            name='r17c6',
            field=models.CharField(default='.', max_length=99, verbose_name='電控-進度三'),
        ),
        migrations.AddField(
            model_name='item003',
            name='r17c7',
            field=models.CharField(default='.', max_length=99, verbose_name='電控-備註說明'),
        ),
        migrations.AddField(
            model_name='item003',
            name='r18c3',
            field=models.CharField(default='.', max_length=99, verbose_name='自動噴霧-零件'),
        ),
        migrations.AddField(
            model_name='item003',
            name='r18c4',
            field=models.CharField(default='.', max_length=99, verbose_name='自動噴霧-進度一'),
        ),
        migrations.AddField(
            model_name='item003',
            name='r18c5',
            field=models.CharField(default='.', max_length=99, verbose_name='自動噴霧-進度二'),
        ),
        migrations.AddField(
            model_name='item003',
            name='r18c6',
            field=models.CharField(default='.', max_length=99, verbose_name='自動噴霧-進度三'),
        ),
        migrations.AddField(
            model_name='item003',
            name='r18c7',
            field=models.CharField(default='.', max_length=99, verbose_name='自動噴霧-備註說明'),
        ),
        migrations.AddField(
            model_name='item003',
            name='r19c3',
            field=models.CharField(default='.', max_length=99, verbose_name='自動取出-零件'),
        ),
        migrations.AddField(
            model_name='item003',
            name='r19c4',
            field=models.CharField(default='.', max_length=99, verbose_name='自動取出-進度一'),
        ),
        migrations.AddField(
            model_name='item003',
            name='r19c5',
            field=models.CharField(default='.', max_length=99, verbose_name='自動取出-進度二'),
        ),
        migrations.AddField(
            model_name='item003',
            name='r19c6',
            field=models.CharField(default='.', max_length=99, verbose_name='自動取出-進度三'),
        ),
        migrations.AddField(
            model_name='item003',
            name='r19c7',
            field=models.CharField(default='.', max_length=99, verbose_name='自動取出-備註說明'),
        ),
        migrations.AddField(
            model_name='item003',
            name='r20c3',
            field=models.CharField(default='.', max_length=99, verbose_name='自動切邊去毛-零件'),
        ),
        migrations.AddField(
            model_name='item003',
            name='r20c4',
            field=models.CharField(default='.', max_length=99, verbose_name='自動切邊去毛-進度一'),
        ),
        migrations.AddField(
            model_name='item003',
            name='r20c5',
            field=models.CharField(default='.', max_length=99, verbose_name='自動切邊去毛-進度二'),
        ),
        migrations.AddField(
            model_name='item003',
            name='r20c6',
            field=models.CharField(default='.', max_length=99, verbose_name='自動切邊去毛-進度三'),
        ),
        migrations.AddField(
            model_name='item003',
            name='r20c7',
            field=models.CharField(default='.', max_length=99, verbose_name='自動切邊去毛-備註說明'),
        ),
    ]
