# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-18 08:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app001', '0026_auto_20160817_0820'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item001',
            name='field1',
            field=models.CharField(max_length=200, primary_key=True, serialize=False, verbose_name='幾號機'),
        ),
        migrations.AlterField(
            model_name='item002',
            name='field4',
            field=models.CharField(default='.', max_length=200, verbose_name='計劃交貨日期'),
        ),
        migrations.AlterField(
            model_name='item002',
            name='field5',
            field=models.CharField(default='.', max_length=200, verbose_name='客戶需求數'),
        ),
        migrations.AlterField(
            model_name='item002',
            name='field6',
            field=models.CharField(default='.', max_length=200, verbose_name='實際出貨數'),
        ),
        migrations.AlterField(
            model_name='item002',
            name='field7',
            field=models.CharField(default='.', max_length=200, verbose_name='延交數量'),
        ),
    ]
